# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Antidote' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  # pod 'Firebase/Messaging'
  # Pods for Antidote

  target 'AntidoteTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
